server:
  port: 8084
spring:
  application:
    name: file-service

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1

fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image: # 缩略图
    width: 60
    height: 60
  tracker-list: # tracker地址
    - 120.78.151.253:22122

ab:
  upload:
    baseUrl: "https://www.unow.top/"
    maxSize: 10240
    allowTypes:
      - image/jpeg
      - image/png
      - image/bmp