server:
  port: 8081

spring:
  application:
    name: label-service
  datasource:
    url: jdbc:mysql://localhost:3306/new_aibrainer?useUnicode=true&characterEncoding=UTF8
    password: root
    username: root

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


#  rabbitmq:
#    host: 127.0.0.1
#    username: aibrainer
#    password: aibrainer
#    virtual-host: /aibrainer
    #模板


